apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq-operator
    server: 'https://172.18.0.4:6443'
  project: default
  sources:
  - chart: rabbitmq-cluster-operator
    #helm:
      #valueFiles:
      #- $github_ref/values/values.yaml
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.10.7
  - ref: github_ref
    repoURL: https://github.com/angelapoliana/teste_sympla.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true