apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: 'https://172.18.0.4:6443'
  project: default
  sources:
  - chart: grafana
    helm:
      valueFiles:
      - $github_ref/values/values.yaml
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 7.0.14
  - ref: github_ref
    repoURL: https://github.com/angelapoliana/teste_sympla.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
