apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq
    server: 'https://172.18.0.4:6443'
  project: default
  sources:
  - chart: rabbitmq
    helm:
      valueFiles:
      - $github_ref/values/values-rabbitmq.yaml
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.5.6
  - ref: github_ref
    repoURL: https://github.com/angelapoliana/teste_sympla.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    post:
      - command: ['kubectl', 'apply', '-f', 'update-secret.yaml', '-n', 'rabbitmq']